#!/bin/bash
#
# MoeNUTS Show Doc Script... use Control-X To Exit Viewer
# If this script is not executable, use:  chmod 744 show 
#
clear
echo Viewing: $1... 
echo ""
echo -n Press Control-X To Exit Viewer...
sleep 2
echo ""
echo ""
cp $1 "Moenuts: $1.gz"   # Temporarily Copy File
gunzip "Moenuts: $1.gz"  # Unzip Temporary File As We Cannot View .gz files
pico -x -v "Moenuts: $1" # Show The Temporary File
rm -f "Moenuts: $1"      # Remove The Temporary File
# End Of Script...
