
char *command[]={
"quit",         "look",       "mode",        "say",       "shout",
"tell",         "emote",      "semote",      "pemote",    "echo",
"go",           "ignore",     "prompt",      "main",      "listen",
"ignall",       "public",     "private",     "knock",     "invite",
"to",           "move",       "bcast",       "who",       "people",
"help",         "shutdown",   "news",        "read",      "write",
"wipe",         "search",     "review",      "email",     "stat",
"version",      "rmail",      "smail",       "dmail",     "from",
"entpro",       "examine",    "lastlogin",   "rooms",     "makeuser",
"finduser",     "lastcbuff",  "nslookup",    "passwd",    "kill",
"promote",      "demote",     "listbans",    "ban",       "unban",
"vis",          "invis",      "site",        "wake",      "wiztell",
"muzzle",       "unmuzzle",   "map",         "logging",   "minlogin",
"system",       "charecho",   "clearline",   "fix",       "unfix",
"viewlog",      "viewsys",    "cbuff",       "clone",     "destroy",
"myclones",     "allclones",  "switch",      "csay",      "chear",
"cemote",       "swban",      "desc",        "cls",       "color",
"inphr",        "outphr",     "suicide",     "nuke",      "reboot",
"recount",      "revtell",    "think",       "wemote",    "imnew", 
"staff",        "management", "calender",    "entroom",   "topic",
"accreq",       "boot",       "arrest",      "unarrest",  "gender",  
"rules",        "srules",     "record",      "change",    "revwiz",
"chrank",       "beep",       "afk",         "join",      "mash", 
"freeze",       "unfreeze",   "sing",        "naked",     "ssing",
"doh",          "qecho",      "hug",         "force",     "kiss",
"french",       "netsex",     "netsextwo",   "yell",      "logoff",
"clsall",       "welcome",    "time",        "ranks",     "greet",
"samesite",     "wrap",       "uninvite",    "streak",    "lick",
"bop",          "set",        "paddle",      "tictactoe", "finger",
"prules",       "startpoker", "joinpoker",   "leavepoker","gamespoker",
"dealpoker",    "foldpoker",  "betpoker",    "checkpoker","raisepoker",
"discpoker",    "seepoker",   "handpoker",   "rankpoker", "friends",
"scorepoker",   "talkers",    "plist",       "ptell",     "rpic",
"vpic",         "wcbuff",     "scbuff",      "revshout",  "homeroom",
"edit",         "rmkill",     "rmban",       "rmunban",   "rmgive",
"muds",         "ewtoo",      "nuts",        "shackle",   "unshackle",
"makeinvis",    "makevis",    "hide",        "show",      "execall",
"craps",        "cash",       "lend",        "atmosedit", "backup",
"hangman",      "guess",      "pets",        "tpromote",  "socials",
"icqpage",      "toemote",    "addnews",     "figlet",    "sreboot",
"ctopic",       "alias",      "wire",	     "blah",      "rebuild",
"brand",        "unbrand",    "capture",     "slots",     "trivia",
"twin",         "question",   "answer",      "keys",      "roomcap",
"dictionary",   "steal",      "spin",        "coinflip",  "rolldice",
"fight",        "cfight",     "russian",     "paintball", "reloadpaint",
"eightball",    "mutter",     "revmutter",   "cmutter",   "textcolour",
"makeuserpages","con4",       "takecash",    "use",       "objects",
"roomobj",      "userobj",    "rloadobj",    "inspect",   "get",
"drop",         "trash",      "giveobj",     "drink",     "eat",
"wear",         "objinfo",    "botlogin",    "warnuser",  "guarddog",
"files",        "spod",       "tspod",       "respod",    "richlist",
"thieflist",    "wtell",      "afflist",     "ticlist",   "fightlist",
"accept",       "ftell",      "*"
};

/* Values of commands , used in switch in exec_com() */
enum comvals {
QUIT,        LOOK,         MODE,         SAY,         SHOUT,
TELL,        EMOTE,        SEMOTE,       PEMOTE,      ECHO,
GO,          IGNORE,       PROMPT,       LOBBY,       LISTEN,
IGNALL,      PUBCOM,       PRIVCOM,      KNOCK,       INVITE,
TO,          MOVE,         BCAST,        WHO,         PEOPLE,
HELP,        SHUTDOWN,     NEWS,         READ,        WRITE,
WIPE,        SEARCH,       REVIEW,       EMAIL,       STATUS,
VER,         RMAIL,        SMAIL,        DMAIL,       FROM,
ENTPRO,      EXAMINE,      LASTLOGIN,    RMST,        MAKEUSER,
FINDUSER,    CLASTLOGIN,   NSLOOKUP,     PASSWD,      KILL,
PROMOTE,     DEMOTE,       LISTBANS,     BAN,         UNBAN,
VIS,         INVIS,        SITE,         WAKE,        WIZTELL,
MUZZLE,      UNMUZZLE,     MAP,          LOGGING,     MINLOGIN,
SYSTEM,      CHARECHO,     CLEARLINE,    FIX,         UNFIX,
VIEWLOG,     VIEWSYS,      CBUFF,        CREATE,      DESTROY,
MYCLONES,    ALLCLONES,    SWITCH,       CSAY,        CHEAR,
CEMOTE,      SWBAN,        DESC,         CLS,         COLOR,
INPHRASE,    OUTPHRASE,    SUICIDE,      NUKE,        REBOOT,
RECOUNT,     REVTELL,      THINK,        WEMOTE,      IMNEW,
STAFF,       MANAGEMENT,   CALENDER,     ENTROOM,     TOPIC,
ACCREQ,      BOOT,         ARREST,       UNARREST,    GENDER,
RULES,       SRULES,       RECORD,       CHANGE,      REVWIZ,
SETRANK,     BEEP,         AFK,          JOIN,        GAG,
FREEZE,      UNFREEZE,     SING,         NAKED,       SSING,
DOH,         QECHO,        HUG,          FORCE,       KISS,
FRENCH,      NETSEX,       NETSEXTWO,    YELL,        LOGOFF,
CLSALL,      WELCOME,      TIME,         RANKS,       GREET,
SAMESITE,    WRAP,         UNINVITE,     STREAK,      LICK,
BOP,         SET,          PADDLE,       TICTAC,      FINGER,
POKER,       STARTPO,      JOINPO,       LEAVEPO,     GAMESPO,
DEALPO,      FOLDPO,       BETPO,        CHECKPO,     RAISEPO,
DISCPO,      SEEPO,        HANDPO,       RANKPO,      FRIENDS,
SCOREPO,     TALKERS,      PICLIST,      PICTELL,     ROOMPIC,
VIEWPIC,     WREVCLR,      SREVCLR,      REVSHOUT,    MYROOM,
EDIT,        RMKILL,       RMBAN,        RMUNBAN,     GIVEROOM,
MUDS,        EWTOO,        NUTS,         SHACKLE,     UNSHACKLE,
MAKEINVIS,   MAKEVIS,      HIDE,         SHOW,        ALLEXEC,
CRAPS,       GIVECASH,     LENDCASH,     ATMOS,       BACKUP,
HANGMAN,     GUESS,        LOOKPETS,     TPROMOTE,    SOCIALS,
ICQPAGE,     TOEMOTE,      ADDNEWS,      FIGLET,      SREBOOT,
CTOPIC,      ALIAS,        WIRE,	 BLAH,	      REBUILD,
BRAND,       UNBRAND,	   CAPTURE,	 SLOTS,       TRIVSTART,
TRIVWIN,     TRIVQUEST,    TRIVANSWER,   KEYS,        ROOMCAP,
DICTIONARY,  STEAL,        SPIN,         FLIPCOIN,    ROLLDICE,
FIGHT,       FIGHTRESET,   RROULETTE,    PAINTBALL,   PBRELOAD,
EIGHTBALL,   MUTTER,       REVMUTTER,    CMUTTER,     TEXTCOLOR,
MAKEUPAGES,  CONNECTFOUR,  TAKECASH,     USE,         OBJECTS,
ROOMOBJ,     USEROBJ,      RLOADOBJ,     INSPECT,     GET,
DROP,        TRASH,        GIVE,         DRINK,       EAT,
WEAR,        OBJINFO,      LOGINBOT,     WARNUSER,    GUARDDOG,
INFOFILES,   SPOD,         TSPOD,        RESPOD,      RICHLIST,
THIEFLIST,   WTELL,        AFFLIST,      TICLIST,     FIGHTLIST,
ACCEPT,      FRIENDTELL
} com_num;

/* These are the minimum levels at which the commands can be executed.
   Alter to suit. */

int com_level[]={
NEW,        NEW,         NEW,         NEW,        USER,
USER,       USER,        USER,        USER,       USER,
USER,       USER,        NEW,         NEW,        USER,
USER,       USER,        USER,        USER,       USER,
USER,       WIZ,         WIZ,         NEW,        WIZ,
NEW,        BEYOND,      USER,        NEW,        USER,
WIZ,        USER,        USER,        USER,       NEW,
NEW,        NEW,         USER,        USER,       USER,
NEW,        USER,        USER,        USER,       ARCH,
USER,       ARCH,        USER,        USER,       ARCH,
WIZ,        ARCH,        WIZ,         WIZ,        WIZ,
USER,       USER,        WIZ,         WIZ,        WIZ,
WIZ,        WIZ,         USER,        ARCH,       ARCH,
ARCH,       NEW,         WIZ,         ARCH,       ARCH,
WIZ,        ARCH,        USER,        WIZ,        WIZ,
WIZ,        WIZ,         WIZ,         WIZ,        WIZ,
WIZ,        ARCH,        NEW,         NEW,        NEW,
USER,       USER,        NEW,         ARCH,       BEYOND,
ARCH,       USER,        USER,        WIZ,        NEW,
NEW,        NEW,         NEW,         WIZ,        NEW,
NEW,        WIZ,         WIZ,         WIZ,        ARCH,
NEW,        WIZ,         WIZ,         ARCH,       WIZ,
WIZ,        USER,        USER,        USER,       WIZ,
ARCH,       ARCH,        USER,        USER,       USER,
USER,       GAMES,       USER,        ARCH,       USER,
USER,       USER,        USER,        WIZ,        WIZ,
WIZ,        USER,        NEW,         NEW,        USER,
WIZ,        NEW,         USER,        USER,       USER,
USER,       NEW,         USER,        USER,       GOD,
USER,       USER,        USER,        USER,       USER,
USER,       USER,        USER,        USER,       USER,
USER,       USER,        USER,        USER,       USER,
USER,       USER,        USER,        USER,       WIZ,
USER,       ARCH,        WIZ,         USER,       USER,
USER,       USER,        GOD,         GOD,        GOD,
USER,       USER,        USER,        WIZ,        WIZ,
WIZ,        WIZ,         USER,        WIZ,        USER,
USER,       GAMES,       USER,        USER,       GOD,
USER,       USER,        USER,        ARCH,       MEMBER,
USER,       USER,        ARCH,        USER,       GOD,
USER,       WIZ,	 USER,        USER,       GOD,
MEMBER,     WIZ,	 USER,        USER,       GAMES,
GAMES,      GAMES,       USER,        USER,       WIZ,
USER,       USER,        USER,        USER,       USER,
USER,       USER,        USER,        USER,       USER,
USER,       USER,        GOD,         GOD,        USER,
GOD,        USER,        ARCH,        USER,       ARCH,
ARCH,       ARCH,        ARCH,        USER,       USER,
USER,       USER,        USER,        USER,       USER,
USER,       WIZ,         ARCH,        WIZ,        USER,
USER,       USER,        USER,        ARCH,       USER,
USER,       WIZ,         USER,        USER,       USER,
USER,       USER
};
